### ISSUE TITLE
pretrained model?

### ISSUE THREAD

**Issue by HeChengHui** [Xiaobin-Rong/lite-rtse#1]
@Xiaobin-Rong 
Hello, i am interested in trying out your lite-rtse method. Will you be able to provide a pretrained model to test out?

**Comment by Xiaobin-Rong** [comment]
Well, since I only trained Lite-RTSE on the small VCTK-DEMAND dataset, I'm not very confident in its ability to generalize. Anyway, here is a checkpoint containing pretrained parameters. The useage is as follows:
ckpt_name = 'model_0065.tar'
model = LiteRTSE().cuda().eval()
state_dict = torch.load(ckpt_name, map_location='cuda')['model']
model.load_state_dict(state_dict)
[model_0065.zip](https://github.com/Xiaobin-Rong/lite-rtse/files/13434832/model_0065.zip)

**Comment by HeChengHui** [comment]
@Xiaobin-Rong 
understand that this is an unofficial implementation, but have you tried to make it work in causal/live stream?

**Comment by Xiaobin-Rong** [comment]
No, I have not attempted to convert the model into a streaming format. In fact, I found that the results I reproduced did not meet the performance claimed in the original paper, so I lost interest in this model.

**Comment by HeChengHui** [comment]
@Xiaobin-Rong 
I see thank you!

**Comment by Xiaobin-Rong** [comment]
@HeChengHui
You're welcome!
